### ISSUE TITLE
Picture of the badge? Info about its hardware?

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [ghewgill/ledbadge#1]
The link to http://codemania.co.nz/badge.html is broken. I also tried http://codemania.io/badge.html. It's been a few years so it's probably a long shot but can you provide a picture or specs on the hardware? Maybe you archived something that the Wayback Machine didn't?

**Comment by ghewgill** [comment]
Sorry, I don't know if I even have the badge today. All I have left is this repo and whatever links from https://web.archive.org/web/20121110212733/http://codemania.co.nz/badge.html still work (not many, unfortunately).
